version: '3.3'
services:
  refero:
    build: ./refero
    environment:
      DEBUG: refero:*
    volumes:
      - refero_node_modules:/usr/src/node_modules
      - ./refero:/usr/src
  nuntius:
    build: ./nuntius
    depends_on:
      - refero
    environment:
      DEBUG: nuntius:*
    ports:
      - 3000:3000
    volumes:
      - nuntius_node_modules:/usr/src/node_modules
      - ./nuntius:/usr/src
volumes:
  refero_node_modules:
  nuntius_node_modules:
